version: 2.1
commands:
  setup:
    steps:
      - checkout
      - run:
          name: Setup qemu and buildx
          command: |
            apt-get update; sudo apt-get install -y qemu-user-static binfmt-support
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
      - run:
          name: Check versions
          command: |
            qemu-aarch64-static --version
            update-binfmts --display
jobs:
  build:
    docker:
      - image: peregin/circleci:latest
        user: root
    resource_class: small
    environment:
      JVM_OPTS: -Xmx3072m
      DOCKER_BUILDKIT: 1  # Enable BuildKit
    steps:
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: false
      - run:
          name: Enable Docker buildx
          command: export DOCKER_CLI_EXPERIMENTAL=enabled
      - run:
          name: Build ARM docker
          command: |
            docker buildx use arm-builder
            docker buildx build --platform linux/amd64,linux/arm64 -t arm-image .
workflows:
  version: 2
  build:
    jobs:
      - build