version: 2.1
jobs:
  build:
    docker:
      - image: peregin/circleci:latest
    resource_class: small
    environment:
      JVM_OPTS: -Xmx3072m
      DOCKER_BUILDKIT: 1  # Enable BuildKit
    steps:
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: false
      - run:
          name: Install Docker buildx
          command: |
            mkdir -p ~/.docker/cli-plugins
            url="https://github.com/docker/buildx/releases/download/v0.8.0/buildx-v0.8.0.linux-amd64"
            curl -sSL -o ~/.docker/cli-plugins/docker-buildx $url
            chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run:
          name: Enable Docker buildx
          command: export DOCKER_CLI_EXPERIMENTAL=enabled
      - run:
          name: Build ARM docker
          command: |
            docker buildx install
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create arm-builder
            docker buildx create arm-builder --use
            docker buildx build --platform linux/amd64,linux/arm64 --load -t arm-image .
workflows:
  version: 2
  build:
    jobs:
      - build